# 强制使用官方 CDN，不从 GitHub 克隆
source 'https://cdn.cocoapods.org/'

platform :ios, '15.0'

target 'zhihu-daily-app' do
  use_frameworks!

  pod 'Masonry', '~> 1.1.0'
  pod 'AFNetworking', '~> 3.2.1'
  pod 'MJRefresh', '~> 3.7.6'
  pod 'MBProgressHUD', '~> 1.2.0'
  pod 'JSONModel', '~> 1.8.0'
  pod 'SDWebImage', '~> 5.18.3'
  pod 'FMDB', '~> 2.7.12'
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end